version: "3"

set: [pipefail]

tasks:
  default:
    cmds:
      - task: test

  unit-tests:
    desc: Run Go tests
    cmds:
      - go test ./... -v -ginkgo.v

  cluster:
    desc: Deploy test cases to KIND cluster
    vars:
      image: ghcr.io/cni-benchmark/operator:latest
    cmds:
      - CGO_ENABLED=0 go build --ldflags='-s -w' -o dist/cni-benchmark-operator cmd/main.go
      - docker build -t {{ .image }} -f Dockerfile ./dist
      - task: kind:create
      - task: kind:load
        vars:
          image: "{{ .image }}"

  clean:
    desc: Clean everything
    cmds:
      - task: kind:clean

includes:
  kind:
    taskfile: ./kind/taskfile.yaml
    dir: ./kind
