apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test-cases
  namespace: default
spec:
  sourceRef:
    kind: GitRepository
    name: test-cases
    namespace: flux-system
  path: ./kubernetes/tests
  force: true
  interval: 1h
  prune: true
  timeout: 2m
  wait: false
  patches:
    - target:
        kind: Job
      patch: |-
        - op: replace
          path: /spec/template/spec/containers/0/imagePullPolicy
          value: Never
    - target:
        kind: Job
        labelSelector: mode=client
      patch: |-
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: INFLUXDB_URL
            value: http://influxdb.default
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: INFLUXDB_TOKEN
            value: token
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: INFLUXDB_ORG
            value: primary
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: INFLUXDB_BUCKET
            value: primary
