name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install iperf3
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |-
          sudo apt-get update -qqy
          sudo apt-get install -qqy iperf3

      - name: Make reports folder
        run: mkdir -p reports

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --config .golangci.yaml --out-format json > reports/golangci-lint.json

      - name: Vet
        run: go vet --json ./... > reports/govet.out

      - name: Install packages
        run: go mod tidy

      - name: Unit and E2E tests
        run: go test -v ./... --ginkgo.v --coverprofile=reports/coverage.out

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: reports/coverage.out
