name: Test

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Make reports folder
        run: mkdir -p reports

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --config .golangci.yaml --out-format json > reports/golangci-lint.json
  
  vet:
    runs-on: ubuntu-latest
    name: Vet
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Make reports folder
        run: mkdir -p reports

      - name: Vet
        run: go vet --json ./... > reports/govet.out

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Make reports folder
        run: mkdir -p reports

      - name: Cache GOBIN
        uses: actions/cache@v4
        with:
          path: bin
          key: ${{ runner.os }}-gobin
          restore-keys: |
            ${{ runner.os }}-gobin

      - name: Update path and env
        env:
          BIN: ${{ github.workspace }}/bin
        run: |-
          echo "$BIN" | tee -a "$GITHUB_PATH"
          echo "GOBIN=$BIN" | tee -a "$GITHUB_ENV"

      - name: Install packages
        run: go mod tidy

      - name: Install iperf3
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |-
          sudo apt-get update -y
          sudo apt-get install -y iperf3

      - name: Setup envtest
        run: |-
          version="$(curl -fsSL https://dl.k8s.io/release/stable.txt | awk -F. '{print $1"."$2".x!"}' | tr -d v)"
          go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
          echo "KUBEBUILDER_ASSETS=$(setup-envtest use "$version" --bin-dir "$GOBIN" -p path)" | tee -a "$GITHUB_ENV"

      - name: Unit and E2E tests
        run: go test -v ./... --ginkgo.v --coverpkg=./... --coverprofile=reports/coverage.out

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: reports/coverage.out
